apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: task06-1
spec:
  selector:
    matchLabels:
      name: task06-1
  template:
    metadata:
      labels:
        name: task06-1
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: HTTP_PORT
          value: "8080"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
